export { default as Home } from '@/assets/Home 1.svg?react';
export { default as Profile } from '@/assets/Profile 1.svg?react';
export { default as Scroll } from '@/assets/Scroll.svg?react';
export { default as Toolbox } from '@/assets/Toolbox.svg?react';
export { default as Article } from '@/assets/Article.svg?react';
export { default as Logo } from '@/assets/logo.svg?react';
export { default as MessageNotification } from '@/assets/message-notif.svg?react';
export { default as Notification } from '@/assets/notification.svg?react';
export { default as Calendar } from '@/assets/calendar.svg?react';
export { default as Calculator } from '@/assets/calculator.svg?react';
export { default as Setting } from '@/assets/setting-4.svg?react';
export { default as TrendUp } from '@/assets/trend-up.svg?react';
export { default as Frame } from '@/assets/frame.svg?react';
export { default as HeaderText } from '@/assets/Header text.svg?react';
export { default as Sketch } from '@/assets/Sketch.png';
